on:
  poll:
    url: https://api.github.com/users/yyolk/events
    config:
      every: '0 3 * * *'  # 9pm CST, 3AM UTC
      manualRunEvent: workflow_dispatch
      limit: 1
      filterScript: |
        if (item.type === "PushEvent" && (new Date() - new Date(item.created_at)) / (1000 * 60 * 60 * 24) < 1) {
          return true
        }

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          sample: ${{ on.poll.outputs.payload.commits[0].url }}
        run: echo "$sample"
  complete_taskade_task:
    name: Complete Taskade Task
    runs-on: ubuntu-latest
    steps:
      - name: Complete Taskade Task
        uses: actionsflow/axios@v1
        with:
          url: https://www.taskade.com/api/v1/projects/${{ secrets.TASKADE_PROJECTID_REOCCURRING }}/tasks/${{ secrets.TASKADE_TASKID_REOCCURRING_PUSH_SOMETHING_TO_GITHUB }}/complete
          method: POST
          bearer-token: ${{ secrets.TASKADE_PAT }}
          data: '{}'
