on:
  poll:
    url: https://api.github.com/users/yyolk/events
    config:
      every: '0 3 * * *'  # 9pm CST, 3AM UTC
      manualRunEvent: workflow_dispatch
      filterScript: |
        if (item.type === "PushEvent" && (new Date() - new Date(item.created_at)) / (1000 * 60 * 60 * 24) < 1) {
          return true
        }

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          sample: ${{ on.poll.outputs.payload.commits[0].url }}
        run: echo "$sample"