on:
  rss:
    url: https://status.taskade.com/history.rss
    config:
      force: true
      manualRunEvent: workflow_dispatch
jobs:
  print_and_pushover_notify:
    name: Print and Pushover Notify
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          content: ${{on.rss.outputs.content}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo content: $content
          echo link: $link
      - name: Axios Action POST
        uses: actionsflow/axios@v1
        with:
          url: https://api.pushover.net/1/messages.json
          method: POST
          data: >-
            {
            "token": "${{ secrets.PUSHOVER_API_TOKEN }}",
            "user": "${{ secrets.PUSHOVER_USER_KEY }}",
            "title": "Taskade Status: ${{on.rss.outputs.title}}",
            "message": "${{on.rss.outputs.content}}",
            "html": 1,
            "url": "${{on.rss.outputs.link}}",
            "url_title": "Read more...",
            "sound": "climb"
            }
