on:
  script:
    # run: |
    #   const result = {"id": Math.random().toString(36).substring(7), "d": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"}
    #   return [result]
    # deduplicationKey: id
    run: |
      return [{}]
    config:
      manualRunEvent: workflow_dispatch
      force: true
      shouldDeduplicate: false
      # turned off = false
      active: true
jobs:
  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: jo
      #     version: 1.0
      - name: update curl version
        run: |
          sudo add-apt-repository ppa:savoury1/backports -y
          sudo apt-get update
          sudo apt-get install --only-upgrade -y curl
      - name: Echo Curl Version
        run: curl -V    
      - name: Install jo
        env:
          JO_VERSION: "1.9"
        run: |
          curl -L https://github.com/jpmens/jo/releases/download/$JO_VERSION/jo-$JO_VERSION.tar.gz | tar xvz
          cd jo-$JO_VERSION
          autoreconf -i
          ./configure
          make check
          make install
          jo -v
      - name: Echo
        env:
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          content: "<b>this is <em>variety</em></b>"
          link: "https://google.com"
          title: "Test Title"
        # run: >-
        #   curl -s
        #   --form-string "token=$PUSHOVER_API_TOKEN"
        #   --form-string "user=$PUSHOVER_USER_KEY"
        #   --form-string "message=hello world, from actionsflow"
        #   https://api.pushover.net/1/messages.json
        run: >-
          jo -p
          token="$PUSHOVER_API_TOKEN"
          user="$PUSHOVER_USER_KEY"
          title="$title"
          message="$content"
          html="1"
          url="$link"
          url_title="Read more..."
          | 
          curl -s
          -X POST
          --json @-
          https://api.pushover.net/1/messages.json
