on:
  script:
    # run: |
    #   const result = {"id": Math.random().toString(36).substring(7), "d": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"}
    #   return [result]
    # deduplicationKey: id
    run: |
      return [{}]
    config:
      manualRunEvent: workflow_dispatch
      force: true
      shouldDeduplicate: false
      # turned off
      active: false
jobs:
  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          content: "<b>this is <em>variety</em></b>"
          link: "https://google.com"
          title: "Test Title"
        # run: >-
        #   curl -s
        #   --form-string "token=$PUSHOVER_API_TOKEN"
        #   --form-string "user=$PUSHOVER_USER_KEY"
        #   --form-string "message=hello world, from actionsflow"
        #   https://api.pushover.net/1/messages.json
        run: >-
          curl -s
          -X POST
          -H "Content-Type: application/json"
          -d '{
          "token": "$PUSHOVER_API_TOKEN",
          "user": "$PUSHOVER_USER_KEY",
          "title": "$title",
          "message": "$content",
          "html": 1,
          "url": "$link",
          "url_title": "Read more..."
          }'
          https://api.pushover.net/1/messages.json
